In [16]:
#Problem
#You want to create a vector.

#Solution
#Use NumPy to create a one-dimensional array:

# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

#NOTE: vector is a one-dimensional array
print (vector_row)
print (vector_column)


[1 2 3]
[[1]
 [2]
 [3]]


In [17]:
#Problem
#You need to create a matrix.

#Solution
#Use NumPy to create a two-dimensional array:

# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [19]:
#Problem
#Given data with very few nonzero values, you want to efficiently represent it.

#Solution
#Create a sparse matrix:

# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
#print(matrix)
# Create compressed sparse row (CSR) matrix
matrix_sparse= sparse.csr_matrix(matrix)

# Sparse matrices only store nonzero elements 
# assume all other values will be zero, leading to significant computational savings.

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [35]:
#Problem
#You need to select one or more elements in a vector or matrix.

#Solution
#NumPy’s arrays make that easy:

# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Select third element of vector
print(vector[2])

# Select all elements of a vector
print(vector[:])

# Select everything up to and including the third element
print(vector[:3])



# Select everything after the third element
print(vector[3:])


# Select the last element
print(vector[-1])



3
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6


In [36]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


# Select second row, second column
print(matrix[1,1])




5


In [39]:
#Problem
#You want to describe the shape, size, and dimensions of the matrix.

#Solution
#Use shape, size

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
print(matrix.shape)

# View number of elements (rows * columns)
print(matrix.size)



(3, 4)
12


In [64]:
#Problem
#You want to apply some function to multiple elements in an array.

#Solution
#Use NumPy’s vectorize:
#vectorize is essentially a for loop over the elements 

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Add 100 to all elements
matrix=matrix + 100


print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [42]:
#Problem
#You need to find the maximum or minimum value in an array.

#Solution
#Use NumPy’s max and min:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
print(np.max(matrix))

# Return minimum element
print(np.min(matrix))


9
1


In [43]:
# Find maximum element in each column
print(np.max(matrix, axis=0))

# Find maximum element in each row
print(np.max(matrix, axis=1))

[7 8 9]
[3 6 9]


In [44]:
#Problem
#You want to calculate some descriptive statistics about an array.

#Solution
#Use NumPy’s mean, var, and std:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
print(np.mean(matrix))

# Return variance
print(np.var(matrix))


# Return standard deviation
print(np.std(matrix))

5.0
6.666666666666667
2.581988897471611


In [45]:
#Problem
#You want to change the shape (number of rows and columns) of an array without changing the element values.

#Solution
#Use NumPy’s reshape:

# Load library
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
print(matrix.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [46]:
print(matrix.size)

12


In [47]:
#Problem
#You need to transpose a vector or matrix.

#Solution
#Use the T method:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [48]:
# Transpose vector
print(np.array([1, 2, 3, 4, 5, 6]).T)

[1 2 3 4 5 6]


In [50]:
#Problem
#You need to transform a matrix into a one-dimensional array.

#Solution
#Use flatten:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


In [51]:
#Problem
#You need to know the rank of a matrix.

#Solution
#Use NumPy’s linear algebra method matrix_rank:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
print(np.linalg.matrix_rank(matrix))
#Note: https://stattrek.com/matrix-algebra/matrix-rank.aspx

2


In [52]:
#Problem
#You need to know the determinant of a matrix.

#Solution
#Use NumPy’s linear algebra method det:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
print(np.linalg.det(matrix))

#Note: https://stattrek.com/matrix-algebra/matrix-determinant.aspx

0.0


In [53]:
#Problem
#You need to get the diagonal elements of a matrix.

#Solution
#Use diagonal:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
print(matrix.diagonal())

[1 4 9]


In [54]:
#Note: The trace of a matrix is the sum of the diagonal elements 
#Problem
#You need to calculate the trace of a matrix.

#Solution
#Use trace:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
print(matrix.trace())

14


In [55]:
#Note: http://setosa.io/ev/eigenvectors-and-eigenvalues/
#Problem
#You need to find the eigenvalues and eigenvectors of a square matrix.

#Solution
#Use NumPy’s linalg.eig:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eigenvalues
print(eigenvalues)


# View eigenvectors
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [57]:
#Problem
#You need to calculate the dot product of two vectors.

#Solution
#Use NumPy’s dot:

# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
print(np.dot(vector_a, vector_b))

#Note: http://tutorial.math.lamar.edu/Classes/CalcII/DotProduct.aspx

32


In [58]:
#Another way 
print(vector_a @ vector_b)


32


In [59]:
#Problem
#You want to add or subtract two matrices.

#Solution
#Use NumPy’s add and subtract:

# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
print(np.add(matrix_a, matrix_b))

# Subtract two matrices
print(np.subtract(matrix_a, matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [60]:
#another way of doing the same
print(matrix_a + matrix_b)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [61]:
print(matrix_a - matrix_b)

[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [62]:
#Problem
#You want to multiply two matrices.

#Solution
#Use *

# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
print(np.dot(matrix_a, matrix_b))

[[2 5]
 [3 7]]


In [63]:
#Problem
#You want to calculate the inverse of a square matrix.

#Solution
#Use NumPy’s linear algebra inv method:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
print(np.linalg.inv(matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]
